#!/bin/sh

set -eu

URL="http://{{ ip }}/"

case $1 in
    # Implements master-url command locally
    master-url)
	echo $URL
	exit 0
	;;
    wait-master-online)
	exec curl --silent --show-error --head --retry-delay 2 --retry 20 $URL >/dev/null
	;;
    *)
	$0 wait-master-online
	exec java -jar {{ jar }} -s $URL $@
	;;
esac
